name: Links
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install
        run: npm ci

      - name: build
        run: npm run build

      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://briansunter.com
          pages_path: ./dist/
          cmd_params: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --limit-redirections=5 --timeout=20  # muffet parameters
          run_timeout: 600  # maximum amount of time to run muffet (default is set to 300 seconds)
